[package]
name = "hinix"
version = "0.1.0"
authors = ["fpagliughi <fpagliughi@mindspring.com>"]
repository = "https://github.com/fpagliughi/hinix"
license = "MIT"
categories = ["os::unix-apis"]
description = """
High level *nix functionality in Rust.
"""

[dependencies]
nix = "0.11"
libc = "0.2"

